version: "3.7"
services:
  vmangos_database:
    container_name: vmangos_database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - vmangos_database:/var/lib/mysql           #vmangos_database volume
      - ./src/core/sql:/opt/vmangos/sql           #vmangos src
      - ./src/database:/opt/vmangos/sql/database  #vmangos src
    env_file: 
      - ./env/db.env
      - ./env/mangos.env
    restart: always

  vmangos_realmd:
    container_name: vmangos_realmd
    build: 
      context: .
      dockerfile: docker/realmd/Dockerfile
    ports: 
      - 3724:3724
    volumes:
      - ./config/realmd.conf:/opt/vmangos/etc/realmd.conf:ro  #realmd conf
      - ./vmangos/bin/realmd:/opt/vmangos/bin/realmd:ro       #realmd bin
    depends_on:
      - vmangos_database
    restart: always

  vmangos_mangos:
    container_name: vmangos_mangos
    tty: true         #enable terminal with docker attach
    stdin_open: true  #enable terminal with docker attach
    ports: 
      - 8085:8085
    build:
      context: .
      dockerfile: docker/mangos/Dockerfile
    image: vmangos_mangos:latest
    volumes:
      - ./config/mangosd.conf:/opt/vmangos/etc/mangosd.conf:ro  #mangosd conf
      - ./vmangos/bin/mangosd:/opt/vmangos/bin/mangosd:ro       #mangosd bin
      - ./src/data/5875:/opt/vmangos/bin/5875:ro                #dbc
      - ./src/data/vmaps:/opt/vmangos/bin/vmaps:ro              #vmaps
      - ./src/data/maps:/opt/vmangos/bin/maps:ro                #maps
      - ./src/data/mmaps:/opt/vmangos/bin/mmaps:ro              #mmaps
    depends_on:
      - vmangos_database
    env_file:
      - ./env/mangos.env
    restart: always

#Docker-compose volumes
volumes:
  vmangos_database:
